### ISSUE TITLE
Numbering Mistake

### ISSUE THREAD

**Issue by Hotonah** [re-robinson/Cyber-Test-and-Penetration#1]
Hi Mr. Robinson,

I found a mistake on the CSIA 440 M2. These are both labeled number 1.
![image](https://user-images.githubusercontent.com/49422145/55768349-6a032880-5a31-11e9-8aa5-3a09d35d6a9e.png)

**Comment by re-robinson** [comment]
The code was correct, but the rendering was wrong.  However, I moved to bullet points and will give you the credit.
