### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by PeterGriffinisarockstar** [re-robinson/Cyber-Test-and-Penetration#2]
Hello Mr. Robinson,

In the final the description below E8 has a misspelling in it. The misspelled word is employees. The second bug on the final is in the Supplemental Materials you have makes twice in the same sentence.

![Bug](https://user-images.githubusercontent.com/49795292/56440934-00d8ac00-62a0-11e9-9810-17e65dfc7ace.JPG)
 
![Bug1](https://user-images.githubusercontent.com/49795292/56440935-046c3300-62a0-11e9-9d81-6b5abfcb9aa7.JPG)

**Comment by re-robinson** [comment]
Fixed both bugs and credited you 2 extra credit points.
