### ISSUE TITLE
This Bug is from 9: Reporting and Communication 1

### ISSUE THREAD

**Issue by PeterGriffinisarockstar** [re-robinson/Cyber-Test-and-Penetration#3]
Hello Mr. Robinson,

On 9: Reporting and Communication 1 question E10 there is a misspelled word. The word that is misspelt
![Bug2](https://user-images.githubusercontent.com/49795292/56441027-6f1d6e80-62a0-11e9-9e4b-edf6a7149d14.JPG)
 is framework.

**Comment by re-robinson** [comment]
Fixed, closed, and added 1 point extra credit.
