### ISSUE TITLE
Bug Bounty

### ISSUE THREAD

**Issue by Hotonah** [re-robinson/Cyber-Test-and-Penetration#4]
Hello,

Question E2 says What is the difference between spear fishing and whaling? 

 Fishing should be spelled phishing. 

![image](https://user-images.githubusercontent.com/49422145/56871458-274ec380-69d3-11e9-8f8b-57cd49feee3a.png)

**Comment by re-robinson** [comment]
Thank you!  I have fixed it and credited you 1 point.
