### ISSUE TITLE
Perhaps typo?

### ISSUE THREAD

**Issue by Thaddeus-J** [re-robinson/Cyber-Test-and-Penetration#6]
![image](https://user-images.githubusercontent.com/55521556/65209818-08b69b00-da4e-11e9-8745-041c21d82541.png)

I understand this environment is indeed simple however I think the use of the word sample is better here? It has been referred to as a sample environment in most cases. Thank you for your time ~Thaddeus CSIA 440

**Comment by re-robinson** [comment]
I agree.  +1 extra credit.
